# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d690354f177d92e73ddc057be369c10d305372d23f73fc0bab4e78a2ea67de3d85ddd84420c7273e500623f7e786cbb22586c3bf53fec1ab00fa10b06fa6c10d

test:
  secret_key_base: 80ae3d12ca867874d3282ec305302d91986b535cd91ac9d4c9a22c2f040770eb652a04e1ee9029c49dda0b1cd4708538e7dfa7b2132a7dc3c0a301e85722e130

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
